### PR TITLE
Firebase crate added

### PR DESCRIPTION
**Pull request by emreyalvac**

### CODE REVIEW

**Comment by emreyalvac** [comment]
Not for direct actix but can be used with it :)

**Comment by robjtede** [comment]
As its just a link to a rust crate, it doesnt really belong in the readme of this repo.

**Comment by emreyalvac** [comment]
> As its just a link to a rust crate, it doesnt really belong in the readme of this repo.

Link changed.

**Comment by robjtede** [comment]
This is a repo for examples of actix and actix-web usage so this isnt suitable. If you'd like to create an example of how to integrate this into an actix application, we'd consider a PR for it.

**Pull request closed without merging**
