### PR TITLE
update rusqlite in async_db and r2d2 ++

### PR DESCRIPTION
**Pull request by arve0**
rusqlite have some [breaking changes and new features](https://github.com/jgallagher/rusqlite/releases), this PR

1. updates rusqlite in async_db and r2d2 example
2. adds a note about the use of `web::block`
3. deduplicates repetitive code
4. uses the types with `Iterator::collect` to be idiomatic

### CODE REVIEW

**Comment by fafhrd91** [comment]
could you upgrade rusqlite in all examples?

**Comment by arve0** [comment]
Thought I did, only ran async_db and r2d2 example. I see `diesel v1.4.2` has sqlite as transient dependency, will look into it.

**Comment by arve0** [comment]
Diesel is already latest, and requires libsqlite3-sys `< 0.13.0`: https://github.com/diesel-rs/diesel/blob/master/diesel/Cargo.toml#L19

Not sure if upgrading diesel is a major undertaking or not. Having shared dependencies for examples seems to be limiting. Any ideas?

**Comment by fafhrd91** [comment]
you can remove async_db from workspace, but then add it to travis config

**Comment by arve0** [comment]
`cd diesel && cargo check` fails with

```
error: current package believes it's in a workspace when it's not:
current:   actix-examples/diesel/Cargo.toml
workspace: actix-examples/Cargo.toml

this may be fixable by adding `diesel` to the `workspace.members` array of the manifest located at: actix-examples/Cargo.toml
```

Not sure why, can't see any references to workspace in diesel/Cargo.toml, so a bit puzzled about that.

**Comment by fafhrd91** [comment]
remove workspace from actix-examples/diesel/Cargo.toml

**Comment by arve0** [comment]
> remove workspace from actix-examples/diesel/Cargo.toml

I did that: https://github.com/actix/examples/pull/148/commits/0aec31774c48576c28f8390ec4a024c7f6f695d0#diff-d488e04098f2e4da9d4b763714a9e653

**Comment by arve0** [comment]
> remove workspace from actix-examples/diesel/Cargo.toml

I did that: https://github.com/actix/examples/pull/148/commits/0aec31774c48576c28f8390ec4a024c7f6f695d0

**Comment by arve0** [comment]
I've bumped libsqlite3-sys in diesel, https://github.com/diesel-rs/diesel/pull/2102, and bumping seems to be OK. I'll wait to see if that gets merged and released, then update diesel instead of mangling with the workspace.

**Comment by robjtede** [comment]
ping @arve0 the diesel update solves the sqlite-sys version issue

**Comment by arve0** [comment]
Thanks for the ping Rob. I've rebased on master, and removed commit 0aec317 from the branch.

**Comment by JohnTitor** [comment]
Thanks!

**Pull request merged**
