### PR TITLE
 Add example for Mysql client library (MySql database driver) #622

### PR DESCRIPTION
**Pull request by lastemp**
This RESTful Actix Web API example illustrates how to connect to MySQL database using Mysql client library implemented in rust i.e MySql database driver

### CODE REVIEW

**Comment by lastemp** [comment]
add bank

Please find attached a screenshot of one of the apis executed through a curl request.

**Review by robjtede — APPROVED** [review]
thanks for the contibution

i'll be making some changes after it's merged

**Comment by robjtede** [comment]
@lastemp I've made a number of changes to the original. This way is more idiomatic and matches the style of this repo better. For your learning benefit:
- it wraps all database calls in `web::block` so the synchronous DB operations do not block the server worker tasks
- database calls return `Result`s using `mysql`'s error type
- database helpers return `Result`s using a custom type that implements our `ResponseError` trait so they can be turned into error responses
- handlers return `Result`s using `actix_web::Result` so that propagated errors are converted to responses
- restructured modules for better code separation
- HTTP method names have been removed from the paths, eg. POST /addbank -> POST /bank

**Comment by lastemp** [comment]
> @lastemp I've made a number of changes to the original. This way is more idiomatic and matches the style of this repo better. For your learning benefit:
> 
> * it wraps all database calls in `web::block` so the synchronous DB operations do not block the server worker tasks
> * database calls return `Result`s using `mysql`'s error type
> * database helpers return `Result`s using a custom type that implements our `ResponseError` trait so they can be turned into error responses
> * handlers return `Result`s using `actix_web::Result` so that propagated errors are converted to responses
> * restructured modules for better code separation
> * HTTP method names have been removed from the paths, eg. POST /addbank -> POST /bank
> 
> Thanks for getting the raw mysql example started, it's a good addition to this repo.

@robjtede This is amazing work you have done, I will definitely learn from the changes you made. Again thank you.

**Pull request merged**
