### PR TITLE
Add more examples

### PR DESCRIPTION
**Pull request by bevanhunt**
- added redis-docker example
- added diesel-docker example
- added json-simple example
- updated ip in multipart example not to be a variable (cleaner)
- disabled current diesel and json as both are broken currently

### CODE REVIEW

**Comment by leizzer** [comment]
How to dockerize a project in three different ways plus extra touches, I don't think it helps in our efforts for examples.

**Comment by JohnTitor** [comment]
The diesel and json examples on master have worked well now.

**Comment by JohnTitor** [comment]
I feel `json-simple` isn't helpful because it's duplicate to existing json examples and `*-docker` is a bit too specific.

**Comment by bevanhunt** [comment]
I will create a repo for simple(r) examples and PR the link to the README. Thanks for the feedback!

**Pull request closed without merging**
