### PR TITLE
Update databases/postgres/README.md

### PR DESCRIPTION
**Pull request by Raymi306**
Add sudo -u postgres to relevant commands

Add privilege granting step for new user

Add -i flag to curl command to show HTTP response code

I encountered some headaches first time trying to follow the example as a new Postgres user, I hope that these edits will make things more explicit and more likely to work first try without additional troubleshooting or command running.

### CODE REVIEW

**Comment by robjtede** [comment]
Can you describe more about the environment in which the postgres commands failed? Like OS and how postgres is installed / configured. I suspect that adding the sudo lines will not be a universal solution and may confuse a different set of people? Eg. developing on macOS where there will certainly not be a postgres user.

**Comment by Raymi306** [comment]
It failed on both macOS and on Ubuntu 20.04 Windows Subsystem for Linux version. I wrote this on WSL, I may go back and try and follow it from scratch on the Macbook, but I think the commands were not part of the shell environment there and so I was using PGadmin as a work around

**Comment by Raymi306** [comment]
Checking the macbook again, I installed Postgres with the interactive installer listed first at https://www.postgresql.org/download/macosx/ and don't have any of the shell commands like createuser or createdb as a result, or at least they're not on the path by default.

**Comment by Raymi306** [comment]
@robjtede Are the edits I just committed helpful?

**Comment by robjtede** [comment]
Yep, I think they're more universally helpful. Thanks for the perspective and PR.

**Pull request merged**
