### PR TITLE
Fix sqlx_todo CI checks

### PR DESCRIPTION
**Pull request by danitrod**
Switches the example to use sqlite and adds sqlite3 to the CI.

_Closes #412_

### CODE REVIEW

**Comment by robjtede** [comment]
since this adds sqlx back to the workspace, i'd ask that you make clippy happy while we're here :)

**Comment by danitrod** [comment]
My bad, forgot about that. All good now

**Review by JohnTitor — APPROVED** [review]
We still have a mention to postgresql on README (Line 3), it should be replaced as well. Otherwise LGTM 👍

**Comment by danitrod** [comment]
nice catch, good to go now :)

**Comment by JohnTitor** [comment]
We've encountered https://github.com/bheisler/TinyTemplate/pull/17, let's just ignore it.
Thanks for fixing it!

**Pull request merged**
