### PR TITLE
Update to master

### PR DESCRIPTION
**Pull request by botika**
I forgot the `rustfmt` in the CI script. Sorry.

### CODE REVIEW

**Comment by DoumanAsh** [comment]
How `rustfmt` is used in CI?

**Comment by botika** [comment]
It is used for the `yarte` debug output that I have activated. I can remove the debug output from the implementation. It is simply to change the `yarte.toml`. As you prefer

**Comment by DoumanAsh** [comment]
Yeah I think you can remove debug output, there is no need for it in examples

**Comment by botika** [comment]
Done, @DoumanAsh thanks !!

**Comment by botika** [comment]
I have seen that you have already merged to master. 
I migrate the examples in this pull request.

Leave it and I'll ping you.

**Comment by botika** [comment]
@DoumanAsh Ping!!  It should be already. 
I have removed two examples that did not exist from `travis.conf`.

**Comment by DoumanAsh** [comment]
Thanks for switching actix-web dependency to master

**Pull request merged**
