### PR TITLE
Add test to hello-world

### PR DESCRIPTION
**Pull request by allevo**
` .run(&index)?;` is wrong. I don't know how to translate it for `1.x` version.

Could someone help me?

### CODE REVIEW

**Comment by fafhrd91** [comment]
there are two options:

1. test full pipeline, https://github.com/actix/actix-web/blob/1.0/src/route.rs#L435
2. test only handler function, in that case you can use `actix_web::test::block_on(index(req))`

**Comment by allevo** [comment]
I've used `init_service` but I'm able to test the response body. Which is the best way to do that?

Many thanks for the support.

**Comment by allevo** [comment]
Another question: I would like to refactor the code in order to extract the `App::new()...` invocation from the main in order to call it into the test. I don't know which type should be returned by the `create_app` function:

```rust
fn create_app () -> ???? {
    App::new()
        .middleware(middleware::Logger::default())
        .service(web::resource("/index.html").to(|| "Hello world!"))
        .service(web::resource("/").to(index));
}
```

In this way the main could be written with
```
    HttpServer::new(|| create_app())
        .bind("127.0.0.1:8080")?
        .run()
```

Thanks

**Comment by fafhrd91** [comment]
`create_app()` is problematic. you would need to write all types that App uses, even with impl Trait
it is not easy. trait aliases will help but it is nightly atm

**Comment by fafhrd91** [comment]
regarding body, we need to add `Stream` impl for `MessageBody` types. 

would you like to create PR for actix-http?

**Comment by allevo** [comment]
> create_app() is problematic. you would need to write all types that App uses, even with impl Trait
> it is not easy. trait aliases will help but it is nightly atm

Ok, but this is a pity.

> regarding body, we need to add Stream impl for MessageBody types.
> would you like to create PR for actix-http?

If I understood correctly is no possible to read the response body at all writing a code like:
```rust
let response = test::call_success(&mut srv, req);
let response_body = response.body().into_bytes();
```
Right?

If I have to send a PR to `actix-http`, could you give me some information about how and where to implement the missing code?

Many thanks

**Pull request closed without merging**
