### PR TITLE
redo json example - make simple

### PR DESCRIPTION
**Pull request by bevanhunt**
The current example is broken and too complex for a simple example.

### CODE REVIEW

**Comment by leizzer** [comment]
If it is broken that is one thing and we need to fix it.
And the complexity you mention is in fact various examples in one file for different needs, each one has its own purpose. I feel like you are taking out examples.

**Comment by fafhrd91** [comment]
this example shows different type json handling. what is the reason for removing?

**Comment by bevanhunt** [comment]
The examples are too complex for a simple hello world for JSON.  Sure we can have another more complicated example(s) in another folder. However, I want to know quickly how to do a JSON hello world. It is not trivial to parse through the code with all the current examples to figure this out quickly.

**Comment by fafhrd91** [comment]
if it complex then create new one, json_helloworld or json_basic.

**Pull request closed without merging**
