### PR TITLE
fix thread block in diesel pack and compatibility in async_pg pack

### PR DESCRIPTION
**Pull request by Icatream**
I don't know how to split these two commits.

The first one is about `pool.get()` block the current thread, i moved it into `web::block` block.

The second commit is a compatibility for windows.

### CODE REVIEW

**Comment by Icatream** [comment]
The single quote was formatted by vscode plugin [toml-formatter](https://marketplace.visualstudio.com/items?itemName=Iceyer.toml-formatter).
Is there any other plugin should i to use?

**Comment by robjtede** [comment]
> Is there any other plugin...

Don't use one, personally. Someone suggested that plugin also removes comments form toml files so maybe not the best choice. None of the other toml files in this repo have single quotes.

**Comment by Icatream** [comment]
That plugin do removes comments, and i haven't find another plugin can format toml, i'll write toml manual now.

**Comment by Icatream** [comment]
So, just create a new pack, write the stop handling in it?

**Comment by Icatream** [comment]
I have wrote a `stop-handling` package and test it.
The stop handling works as it expected in linux.
But in windows, it won't print `SIGINT Received.`, just stopped.
I've followed the explanation in `tokio::signal::windows`.
The only thing worked, is it compiled in windows, as the `async_pg` can't be compiled before adding the compatibility.
Do i need to pull it?

**Comment by Icatream** [comment]
I've got confused by the "ctrl break" and "ctrl c".
This time, it works fine.

**Comment by Icatream** [comment]
I've forgot why do i did this stop handling, seems that it used to have a unix stop handling in `async_pg`, and prevent compile in windows. May be i had some confusing with memory.

**Comment by Dowwie** [comment]
async_pg *did* in fact contain a custom implementation for sigint shutdown and it was a mistake

**Comment by robjtede** [comment]
closing as stale

**Pull request closed without merging**
