### PR TITLE
Add example for Juniper async

### PR DESCRIPTION
**Pull request by arlyon**
Async support is now on master but a release has not been made yet. Still, this example is useful for those wanting to use async now.

### CODE REVIEW

**Comment by JohnTitor** [comment]
I'd like to wait for release but your work is definitely welcome!

**Comment by robjtede** [comment]
just going through PRs here, anything to do with this one now?

**Comment by arlyon** [comment]
I rebased onto master but juniper still hasn't had a release since the async stuff got merged into master, so there's not much we can do right now.

**Comment by robjtede** [comment]
seems to me we've migrated juniper to async since this PR was opened

**Pull request closed without merging**
