### PR TITLE
Added example with very fast compile-time template engine Maud

### PR DESCRIPTION
**Pull request by max-frai**
Recently maud merged responder for their markup type and now we can return template result directly from handler.
Maud is probably the fastest template engine now with very powerful features.

### CODE REVIEW

**Comment by DoumanAsh** [comment]
I would prefer not to depend on git dependencies.
So let's wait for maud actual release with actix support

**Comment by max-frai** [comment]
Sure, I agree with you, also I've updated travis config.
When changes will be merged into master I will update this ticket.

**Comment by fafhrd91** [comment]
@max-frai you should run maud only on nightly

**Comment by DoumanAsh** [comment]
@max-frai ping?

**Comment by fafhrd91** [comment]
outdated

**Pull request closed without merging**
