### PR TITLE
Add first test in json example

### PR DESCRIPTION
**Pull request by allevo**
I would like to start to insert some tests in the examples.
This is first PR.

### CODE REVIEW

**Comment by svenstaro** [comment]
Can you rebase this?

**Comment by allevo** [comment]
The interface changes a bit.
This may take time.
For example, if I want to write something like:
```rust

fn create_app<A, B>() -> App<A, B> 
  where ... // <---- ?
{
    App::new()
        // enable logger
        .wrap(middleware::Logger::default())
        .data(web::JsonConfig::default().limit(4096)) // <- limit size of the payload (global configuration)
        .service(web::resource("/extractor").route(web::post().to(index)))
        .service(
            web::resource("/extractor2")
                .data(web::JsonConfig::default().limit(1024)) // <- limit size of the payload (resource level)
                .route(web::post().to_async(extract_item)),
        )
        .service(web::resource("/manual").route(web::post().to_async(index_manual)))
        .service(
            web::resource("/mjsonrust").route(web::post().to_async(index_mjsonrust)),
        )
        .service(web::resource("/").route(web::post().to(index)))
}
```

How can I define `A` and `B`?

**Comment by fafhrd91** [comment]
only option is `App::configure()`

**Comment by allevo** [comment]
Closing in favor 185

**Pull request closed without merging**
