### PR TITLE
Fixes Incorrect Return of body in multipart example

### PR DESCRIPTION
**Pull request by Daggy1234**
The examples shown simply return the html as the body, without setting the right content-type. this results in no html being rendered, but rather just text.

### CODE REVIEW

**Comment by JohnTitor** [comment]
Looks reasonable to me, could you resolve the merge conflicts?

**Comment by Daggy1234** [comment]
Sure!

**Comment by Daggy1234** [comment]
Oh looks lik

> Looks reasonable to me, could you resolve the merge conflicts?

Done

**Comment by JohnTitor** [comment]
Great, could you also format code with stable rustfmt?

**Review by JohnTitor — APPROVED** [review]
Thanks!

**Pull request merged**
