### PR TITLE
Always send body whole and don't use transfer encoding

### PR DESCRIPTION
**Pull request by svenstaro**
Without doing this, body size would be unknown at the time of sending, causing awc to use transfer encoding which is probably unexpected in most cases.
This change makes behavior more obvious.

### CODE REVIEW

**Comment by svenstaro** [comment]
Please don't merge until @vmalloc has gotten this a look-over since they are the original author and I'd like to hear some thoughts on this.

**Comment by JohnTitor** [comment]
Ping @vmalloc: any thoughts?

**Comment by svenstaro** [comment]
Actually just today I noticed that this isn't quite correct yet either. I'll fix it. Please don't merge.

**Comment by svenstaro** [comment]
Ok, I feel good about merging this now. This should also fix #188.

**Pull request merged**
