### PR TITLE
Arbiter::exec to start TcpServer will not work, simply call it

### LINKED ISSUE #115: websocket-tcp-chat does not open TCP listener
Not sure it's a bug in the example, in Actix or on my Mac but I cannot get the example to listen on TCP port 12345. `session::TcpServer::new` is never executed for some reason.

With the following change it works:
```
-    Arbiter::new().exec(move || {
-        session::TcpServer::new("127.0.0.1:12345", srv);
-        Ok::<_, ()>(())
-    });
+    session::TcpServer::new("127.0.0.1:12345", srv);
```

### PR DESCRIPTION
**Pull request by therealprof**
Fixes #115

Signed-off-by: Daniel Egger <daniel@eggers-club.de>

### CODE REVIEW

**Comment by therealprof** [comment]
@fafhrd91 Any change of getting this simple fix for a broken example applied?

**Comment by therealprof** [comment]
@JohnTitor Mind having a look?

**Comment by JohnTitor** [comment]
Does this tcp listener work correctly now? It seems not to work well on my local. Could you make sure it?

**Comment by therealprof** [comment]
Yes, it works for me after the PR.

**Comment by therealprof** [comment]
The client seems to have an unrelated problem to me but at least the the server listens and receives joins and disconnects from the client.

**Comment by JohnTitor** [comment]
Ah, it seems so, we should fix it later (and I should have noticed that...).

**Comment by JohnTitor** [comment]
Thanks!

**Pull request merged**
