### PR TITLE
Add first test in hello-world example

### PR DESCRIPTION
**Pull request by allevo**
As titled.

This PR introduces a test in hello-world example

### CODE REVIEW

**Comment by fafhrd91** [comment]
could you add it to 1.0 branch. actix-web 0.7 is in maintenance mode

**Comment by allevo** [comment]
Should I fire another PR to request a merge into 1.0 branch and close this ?
Have I understood correctly?

**Comment by fafhrd91** [comment]
let's open new one. i'll merge this one.

**Comment by svenstaro** [comment]
Can you rebase this?

**Comment by allevo** [comment]
See https://github.com/actix/examples/pull/185

**Pull request closed without merging**
