### PR TITLE
Updated basics/docker_sample to v4.

### PR DESCRIPTION
**Pull request by PrivateDave**
Removed deprecated test build target. Readme file updated to reflect the actual state of code. Corrected internal container's and host's exposed port numbers.

### CODE REVIEW

**Comment by robjtede** [comment]
doesnt look like the cargo.toml got updated

**Comment by PrivateDave** [comment]
Found it. Should I withdraw this pull request followed by fix, stash and subsequent new PR?

**Comment by robjtede** [comment]
> Should I withdraw this pull request

not necessary, you can just update this PR until it's ready

**Comment by PrivateDave** [comment]
May In squash it into one commit and push with force flag? Will it work since pull request is opened?

**Review by robjtede — APPROVED** [review]
thanks 👍🏻

**Pull request merged**
